apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    gitlab.com/project-slug: ${{values.destination}}
  tags:
    - mroberts
spec:
  type: service
  lifecycle: production
  owner: ${{values.repo.owner | dump}} 