kind: ConfigMap
apiVersion: v1
metadata:
  name: redhat-developer-hub-app-config
  namespace: developer-hub
  uid: 1c35c43c-8656-4414-9847-2e2fe32454d1
  resourceVersion: '4231027'
  creationTimestamp: '2024-07-23T12:22:57Z'
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: redhat-developer-hub
    meta.helm.sh/release-namespace: developer-hub
  managedFields:
    - manager: bridge
      operation: Update
      apiVersion: v1
      time: '2024-07-23T12:42:53Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:meta.helm.sh/release-name': {}
            'f:meta.helm.sh/release-namespace': {}
          'f:labels':
            .: {}
            'f:app.kubernetes.io/managed-by': {}
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2024-07-29T13:07:32Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          'f:app-config.yaml': {}
data:
  app-config.yaml: |
    app:
      baseUrl: ${GITHUB_APP_WEBHOOK_URL}
    backend:
      auth:
        keys:
        - secret: ${BACKEND_SECRET}
      baseUrl: ${GITHUB_APP_WEBHOOK_URL}
      cors:
        origin: ${GITHUB_APP_WEBHOOK_URL}
      database:
        connection:
          password: ${POSTGRESQL_ADMIN_PASSWORD}
          user: postgres
    integrations:
      github:
        - host: github.com
          apps:
            - appId: ${GITHUB_APP_ID}
              clientId: ${GITHUB_APP_CLIENT_ID}
              clientSecret: ${GITHUB_APP_CLIENT_SECRET}
              webhookUrl: ${GITHUB_APP_WEBHOOK_URL}
              webhookSecret: ${GITHUB_APP_WEBHOOK_SECRET}
              privateKey: |
                ${GITHUB_APP_PRIVATE_KEY_FILE}
    auth:
      environment: development
      providers:
        github:
          development:
            clientId: ${GITHUB_APP_CLIENT_ID}
            clientSecret: ${GITHUB_APP_CLIENT_SECRET}
    enabled:
      github: true
      githubOrg: true
    proxy:
      '/argocd/api':
        # url to the api of your hosted argoCD instance
        target: ${ARGOCD_ROUTE}/api/v1/
        changeOrigin: true
        # this line is required if your hosted argoCD instance has self-signed certificate
        secure: false
        headers:
          Cookie:
            $env: argocd.token=${ARGOCD_TOKEN}
    argocd:
      username: admin
      password: ${ARGOCD_PASSWORD}
      appLocatorMethods:
      - instances:
        - name: argocd
          username: admin
          url: ${ARGOCD_ROUTE}
          token: ${ARGOCD_TOKEN}
          baseUrl: https://argocd-server-openshift-gitops.apps.cluster-vhdnd.sandbox2089.opentlc.com
          proxy: '/argocd/api'
        type: config
    catalog:
      providers:
        githubOrg:
          id: development
          githubUrl: "${GITHUB_ORG_URL}"
          orgs: [ "${GITHUB_AUTH_ORG}" ]
      locations:
      - rules:
        - allow:
          - Template
        target: https://github.com/marrober/build-deploy-scaffold/blob/main/01-RHDH-config/showcase-templates.yaml
        type: url
      - rules:
        - allow:
          - Group
          - User
        target: https://github.com/marrober/build-deploy-scaffold/blob/main/01-RHDH-config/org.yaml
        type: url
      - rules:
        - allow:
          - Component
          - System
          - API
          - Resource
          - Location
          - Template
        target: https://github.com/marrober/build-deploy-scaffold/blob/main/01-RHDH-config/catalogs.yaml
        type: url
    kubernetes:
      clusterLocatorMethods:
      - clusters:
        - authProvider: serviceAccount
          name: dev-cluster-infra
          serviceAccountToken: eyJhbGciOiJSUzI1NiIsImtpZCI6IkhkVnhkei0yTXhnWkV5ZnY3bnUwX2tjY3RzMG84WG5Kc1NIaDR6aXAzcFkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZXZlbG9wZXItaHViIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6Imt1YmUtc2EiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjE2YjY0NWVhLTViMDQtNDBkYi04YTA4LTkwNmZkMmU0ZDYwNCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZXZlbG9wZXItaHViOmRlZmF1bHQifQ.QCuGVLPdSkF5Mc852jHqCLB-6kH8mCkULHNMUUfKRkoGgkfOAJfOvgC91Q9WQaZpvcyDCCo7OSZCBHume7kW0fklgtgDy67oIUAgGEKcfQ_YzkbE9Blwp63t_vylzZkxeWwHU3zLnNoIBA7f6bbJ2A_57oXVbiZmEKYiXMfSk7Br4ZU3uMJ89n1pm8EDDWwm2zCcvBuvxJ8KyDWvKjs-2DKw5MF0U7rexEIcULNvXroVMkTnLr2aH1OdKnzRu4rFx5zX98keKJWCjLK-d9encMdrtwEyqjQcDHxSbYC8I9TSiVgt0QYLz4QSBDtIA68ri_qkFf7F084a5r_p2mhqpiDDac1Hr3WS6iAbaoglssFnKHhFOpez-Syc2c5NeDEXGxdhtnpAohJI-AoAKGpD8UxS-jzsC3anGf2bzol6T0Iih2_KqHepZcGReKDCQmaqdMFrxtfZO-Icuwdy5kw2wx5yD7D_pjmd62WPJFXwvv_i3fi2ZdBG457Wfu82zFobea7ZqsJjFgOd8-nyAV9ZJ2CoVN6a2ru8D3gp2lDv2qMuvgZvTvWHZlpn4MuDA4rCmLn1DV_pvJv9tk8KO0S3zlpYkp3Akk648GzB-YIyLFA5cOify4N-GCOSN06qV8ZKLw1Sc-959RTpML49X9FO0mTxXAuusMxEtT172hrsfTE
          skipTLSVerify: true
          url: https://api.cluster-vhdnd.sandbox2089.opentlc.com:6443
        type: config
      customResources:
      - apiVersion: v1beta1
        group: tekton.dev
        plural: pipelineruns
      - apiVersion: v1beta1
        group: tekton.dev
        plural: taskruns
      - apiVersion: v1
        group: route.openshift.io
        plural: routes
      serviceLocatorMethod:
        type: multiTenant
