apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: add-component-template-2
  title: Onboard your component to RHDH-2
  description: Create and register a new component to RHDH Catalog
  tags:
    - bonus
    - rhone
spec:
  owner: rhdh
  type: service
  parameters:
    - title: Provide new component details
      required:
        - component_id
      properties:
        component_id:
          title: Name
          type: string
          maxLength: 20
          pattern: '^[A-Z][A-Za-z0-9_]*$'
        description:
          title: Description
          type: string

    - title: Application repository Information
      required:
        - repo
      properties:
        repo:
          title: Repository Location
          type: object
          properties:
            host:
              title: Repo Host
              type: string
              description: Your SCM host
              default: gitlab-gitlab.apps.cluster-xv8vf.sandbox186.opentlc.com
              enum:
                - gitlab-gitlab.apps.cluster-xv8vf.sandbox186.opentlc.com
            owner:
              title: Repo Owner
              type: string
              description: Your SCM host organization/group
              default: development
              enum:
                - development
  steps:
    - id: log
      name: Log parameters
      action: debug:log
      input: 
        message: 'Parameters -> component_id : ${{ parameters.component_id }} description : ${{ parameters.description }}'
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutTemplating:
          - .github/workflows/*
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          owner: ${{ user.entity.metadata.name }}
          host: ${{ parameters.repo.host }}
          destination: ${{ parameters.repo.owner }}/${{ parameters.component_id }}
          
    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        repoUrl: "${{ parameters.repo.host }}?owner=${{ parameters.repo.owner }}&repo=${{parameters.component_id}}"
        repoVisibility: public

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"
  
  output:
    links:
      - title: Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open Component in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
    message-0: 'Parameters -> component_id : ${{ parameters.component_id }}'
    message-1: 'Parameters -> description  : ${{ parameters.description }}'