apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.environment_name | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
spec:
  type: service
  lifecycle:  ${{values.environment_type | dump}}
  hosting:
    location: ${{values.hosting_location| dump}}
    environment:
      type: ${{values.environment_type | dump}}
      name: ${{values.environment_name | dump}}