apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: ui-template
  title: UI template example
  description: A simple UI example
  tags:
    - recommended
    - java
    - quarkus
    - maven
spec:
  owner: rhdh
  type: service
  parameters:
    - title: Provisioning new instance
      required:
        - environment_type
        - environment_name
        - hosting_location
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
          default: ui-example-app
          ui:field: EntityNamePicker
          maxLength: 20
        artifact_id:
          title: Artifact Id
          type: string
          default: ui-example
          description: Maven Artifact Id
        environment_type:
          title: Environment type
          type: string
          default: INT
          description: What type of environment is this ?
          enum:
            - INT
            - UAT
            - PRE-PROD
            - PROD
        environment_name:
          title: Environment name
          type: string
          description: Name of the environment
          pattern: '^[a-z][a-z0-9_]*$'
        description:
          title: Description
          type: string
          description: A description of the environment
        hosting_location:
          title: Hosting location
          type: string
          default: Germany
          description: Where would you like it hosted ?
          enum:
            - Germany
            - Singapore
            - United Kingdom
            - United States
      dependencies:
        hosting_location:
          oneOf:
            - properties:
                hosting_location:
                  enum: 
                    - United Kingdom
                provider:
                  title: Provider type
                  type: string
                  description: Provider type
                  default: Azure
                  enum:
                    - CMO
                    - Azure
              dependencies:
                provider:
                  oneOf:
                    - properties:
                        provider:
                          enum: 
                          - CMO
                        data_centre:
                          title: Data centre
                          type: string
                          description: Data centre location
                          default: London
                          enum:
                            - London
                            - Birmingham
                            - Manchester
                            - Glasgow
            - properties:
                hosting_location:
                  enum:
                    - Germany
                  provider:
                    ui:widget: hidden
                    default: none
                  data_centre:
                    ui:widget: hidden
                    default: none
    - title: Repository information
      required:
        - repo
      properties:
        repo:
          title: Repository Location
          type: object
          properties:
            host:
              title: Repo Host
              type: string
              description: Your SCM host
              default: gitlab-gitlab.apps.cluster-dmkpx.sandbox1294.opentlc.com
              enum:
                - gitlab-gitlab.apps.cluster-dmkpx.sandbox1294.opentlc.com
            owner:
              title: Repo Owner
              type: string
              description: Your SCM host organization/group
              default: development
              enum:
                - development

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutTemplating:
          - .github/workflows/*
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          namespace: ${{ parameters.component_id }}-dev
          artifact_id: ${{ parameters.artifact_id }}
          java_package_name: ${{ parameters.java_package_name }}
          owner: ${{ user.entity.metadata.name }}
          cluster: .apps.cluster-mxlwg.sandbox1663.opentlc.com
          host: ${{ parameters.repo.host }}
          destination: ${{ parameters.repo.owner }}/${{ parameters.component_id }}
          quay_destination: ${{ parameters.image_organization}}/${{ parameters.component_id }}

    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        repoUrl: "${{ parameters.repo.host }}?owner=${{ parameters.repo.owner }}&repo=${{parameters.component_id}}"
        repoVisibility: public

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

    - id: template-gitops-deployment
      name: Generating Deployment Resources
      action: fetch:template
      input:
        url: ./manifests
        copyWithoutTemplating: []
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          destination: https://${{ parameters.repo.host }}/${{ parameters.repo.owner }}/${{parameters.component_id}}-gitops.git
          source_repository: https://${{ parameters.repo.host }}/${{ parameters.repo.owner }}/${{parameters.component_id}}.git
          repository_name: ${{parameters.component_id}}
          git_owner: ${{ parameters.repo.owner }}
          cluster: .apps.cluster-mxlwg.sandbox1663.opentlc.com
          namespace: ${{ parameters.component_id }}-dev
          image_registry: ${{ parameters.image_registry }}
          image_host: ${{ parameters.image_host }}
          image_organization: ${{ parameters.image_organization }}
          image_name: ${{ parameters.component_id }}
          image_tag: ${{ parameters.image_tag }}
          port: 8080
          repository_host: ${{ parameters.repo.host }}
          deployment_name: quarkus-template
          user: ${{ user.entity.metadata.name }}
        targetPath: ./tenant-gitops

    - id: publish-gitops
      name: Publishing to Resource Repository
      action: publish:gitlab
      input:
        repoUrl: "${{ parameters.repo.host }}?owner=${{ parameters.repo.owner }}&repo=${{parameters.component_id}}-gitops"
        title: gitops resources for ${{ parameters.environment_name }}
        description: gitops resources for ${{ parameters.environment_name }}
        sourcePath: ./tenant-gitops
        repoVisibility: public

  output:
    links:
      - title: Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open Component in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
