kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-rhdh
  namespace: devhub
  uid: 14048cc7-c54c-470f-9d4a-d974a4a68333
  resourceVersion: '4886496'
  creationTimestamp: '2024-04-02T14:21:43Z'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2024-04-03T11:41:34Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:app-config-rhdh.yaml': {}
data:
  app-config-rhdh.yaml: |
    app:
      title: Red Hat Developer Hub
      baseUrl: https://rhdh-developer-hub-devhub.apps.conroe.demolab.local/
    integrations:
      github:
        - host: github.com
          apps:
            - appId: ${GITHUB_APP_ID}
              clientId: ${GITHUB_APP_CLIENT_ID}
              clientSecret: ${GITHUB_APP_CLIENT_SECRET}
              webhookUrl: ${GITHUB_APP_WEBHOOK_URL}
              webhookSecret: ${GITHUB_APP_WEBHOOK_SECRET}
              privateKey: |
                ${GITHUB_APP_PRIVATE_KEY_FILE}
    auth:
      environment: development
      providers:
        github:
          development:
            clientId: ${GITHUB_APP_CLIENT_ID}
            clientSecret: ${GITHUB_APP_CLIENT_SECRET}
    enabled:
      github: true
      githubOrg: true
    catalog:
      providers:
        githubOrg:
          id: development
          githubUrl: "${GITHUB_ORG_URL}"
          orgs: [ "rhdh-uk-mr" ]
        aap:
          prod:
            baseUrl: https://lrcaap.lromeroc.demolab.local
            authorization: 'Bearer nZJCW4stuSKmG3f22ECOd5JHXGrBAR'
            owner: default/lromeroc
            system: prod
            schedule: # optional; same options as in TaskScheduleDefinition
              # supports cron, ISO duration, "human duration" as used in code
              frequency: { minutes: 1 }
              # supports ISO duration, "human duration" as used in code
              timeout: { minutes: 1 }
      locations:
      - rules:
        - allow:
          - Template
        target: https://github.com/marrober/build-deploy-scaffold/blob/main/01-RHDH-config/showcase-templates.yaml
        type: url
      - rules:
        - allow:
          - Group
          - User
        target: https://github.com/marrober/build-deploy-scaffold/blob/main/01-RHDH-config/org.yaml
        type: url
      - rules:
        - allow:
          - Component
          - System
          - API
          - Resource
          - Location
          - Template
        target: https://github.com/marrober/build-deploy-scaffold/blob/main/01-RHDH-config/catalogs.yaml
        type: url

    argocd:
      appLocatorMethods:
      - instances:
        - name: main
          password: 7FLprEChz0b2oAVxgDlXeJanMHB6R9Gw
          url: https://openshift-gitops-server-openshift-gitops.apps.conroe.demolab.local
          username: admin
        type: config
