kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-rhdh
data:
  app-config-rhdh.yaml: |
    app:
      title: Red Hat Developer Hub
      baseUrl: ${RHDH_BASE_URL}
    backend:
      auth:
        keys:
        - secret: ${BACKEND_SECRET}
      baseUrl: ${RHDH_BASE_URL}
      cors:
        origin: ${RHDH_BASE_URL}
      database:
        connection:
          password: ${POSTGRESQL_ADMIN_PASSWORD}
          user: postgres
    integrations:
      github:
        - host: github.com
          apps:
            - appId: ${GITHUB_APP_ID}
              clientId: ${GITHUB_APP_CLIENT_ID}
              clientSecret: ${GITHUB_APP_CLIENT_SECRET}
              webhookUrl: ${GITHUB_APP_WEBHOOK_URL}
              webhookSecret: ${GITHUB_APP_WEBHOOK_SECRET}
              privateKey: |
                ${GITHUB_APP_PRIVATE_KEY_FILE}
    auth:
      environment: development
      providers:
        github:
          development:
            clientId: ${GITHUB_APP_CLIENT_ID}
            clientSecret: ${GITHUB_APP_CLIENT_SECRET}
    enabled:
      github: true
      githubOrg: true
    catalog:
      providers:
        githubOrg:
          id: development
          githubUrl: "${GITHUB_ORG_URL}"
          orgs: [ "rhdh-uk-mr" ]
      locations:
      - rules:
        - allow:
          - Template
        target: https://github.com/marrober/build-deploy-scaffold/blob/main/01-RHDH-config/showcase-templates.yaml
        type: url
      - rules:
        - allow:
          - Group
          - User
        target: https://github.com/marrober/build-deploy-scaffold/blob/main/01-RHDH-config/org.yaml
        type: url
      - rules:
        - allow:
          - Component
          - System
          - API
          - Resource
          - Location
          - Template
        target: https://github.com/marrober/build-deploy-scaffold/blob/main/01-RHDH-config/catalogs.yaml
        type: url

    argocd:
      appLocatorMethods:
      - instances:
        - name: main
          password: 7FLprEChz0b2oAVxgDlXeJanMHB6R9Gw
          url: https://openshift-gitops-server-openshift-gitops.apps.conroe.demolab.local
          username: admin
        type: config
