apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "25"
  creationTimestamp: "2024-07-09T11:07:52Z"
  finalizers:
  - argoproj.io/finalizer
  generation: 2
  labels:
    app: argocd
  name: argocd
  namespace: openshift-gitops
  resourceVersion: "2527526"
  uid: fd72ca75-4b41-4e2f-a9e8-738bbfc5e9f5
spec:
  applicationInstanceLabelKey: rht-gitops.com/openshift-gitops
  applicationSet:
    webhookServer:
      ingress:
        enabled: false
      route:
        enabled: false
  controller:
    appSync: 30s
    processors: {}
    sharding: {}
  extraConfig:
    accounts.dh_admin: 'apiKey, login'
    resource.customizations.health.PersistentVolumeClaim: |
      hs = {}
      if obj.status ~= nil then
        if obj.status.phase ~= nil then
          if obj.status.phase == "Pending" then
            hs.status = "Healthy"
            hs.message = obj.status.phase
            return hs
          end
          if obj.status.phase == "Bound" then
            hs.status = "Healthy"
            hs.message = obj.status.phase
            return hs
          end
        end
      end
      hs.status = "Progressing"
      hs.message = "Waiting for PVC"
      return hs
  grafana:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  ha:
    enabled: false
  initialSSHKnownHosts: {}
  monitoring:
    enabled: false
  notifications:
    enabled: true
  prometheus:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  rbac:
    defaultPolicy: role:admin
    policy: |
      g, system:cluster-admins, role:admin
    scopes: '[groups]'
  redis: {}
  repo: {}
  resourceExclusions: |
    - apiGroups:
        - tekton.dev
      clusters:
        - '*'
      kinds:
        - TaskRun
        - PipelineRun
  resourceHealthChecks:
  - check: |
      hs = {}
      hs.status = "Healthy"
      return hs
    group: networking.k8s.io
    kind: Ingress
  server:
    autoscale:
      enabled: false
    grpc:
      ingress:
        enabled: false
    ingress:
      enabled: false
    route:
      enabled: true
      tls:
        termination: reencrypt
    service:
      type: ""
  tls:
    ca: {}
  version: v2.4.11
status:
  applicationController: Running
  applicationSetController: Running
  host: argocd-server-openshift-gitops.apps.cluster-l6kpl.sandbox1352.opentlc.com
  notificationsController: Running
  phase: Available
  redis: Running
  repo: Running
  server: Running
  sso: Unknown
