apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: project-dance-templates
  description: A collection of RHDH templates for Project Dance
spec:
  type: url
  targets:
     - https://github.com/marrober/build-deploy-scaffold/blob/main/ansible/scaffolder-templates/ansible-job/template.yaml
     - https://github.com/marrober/build-deploy-scaffold/blob/main/app-build-deploy-template/template.yaml
     - https://github.com/marrober/build-deploy-scaffold/blob/main/register-component-lab/template.yaml

