apiVersion: v1
kind: Secret
metadata:
  name: ${{ values.application_name }}-repo
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: ${{ values.destination }}